#!/bin/bash

echo "📱 Roman Urdu Language - WhatsApp Auto Reply"
echo "=============================================="
echo ""
echo "👨‍💻 Developer: Kamran Abbas Kazmi"
echo "📧 Email: kamranabbaskazmi@gmail.com"
echo "📞 WhatsApp: +92 346 5149979"
echo ""
echo "💰 PRICES:"
echo "   Pro: Rs. 14,000 / $49"
echo "   Enterprise: Rs. 56,000 / $199"
echo "   Student: 50% OFF (Rs. 7,000)"
echo ""
echo "📞 EasyPaisa/JazzCash: Available"
echo ""
echo "Reply with:"
echo "   1 - To buy Pro"
echo "   2 - To buy Enterprise"
echo "   3 - Student discount"
echo "   4 - Free trial"
echo ""
echo "We'll reply within 5 minutes!"
echo ""
echo "Contact: kamranabbaskazmi@gmail.com"
